name: Nightly Build

on:
  schedule:
    # cronjob that triggers every day at 2PM UTC
    - cron: '0 14 * * *'
  workflow_dispatch:

jobs:
  build_nightly:
    runs-on: windows-latest
    name: Build Nightly
    outputs:
      full_sha: ${{ steps.var.outputs.full_sha }}
      short_sha: ${{ steps.var.outputs.short_sha }}
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup .Net7.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0'

      - name: Setup Nuget
        uses: nuget/setup-nuget@v1

      - name: Restore Packages
        run: nuget restore LSTexpress\LSTexpressCS\LSTexpress.sln

      - name: Build YimMenuAutoChs
        run: msbuild.exe LSTexpress\LSTexpressCS\LSTexpress.sln /p:platform="x64" /p:configuration="Release"
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: LSTexpress-CS
          path:     rubbish\LSTexpress\LSTexpressCS\bin\x64\Release\
        
